export const COMPETITIONS = [
  { id: "bundesliga", name: "1. Bundesliga" },
  { id: "bundesliga2", name: "2. Bundesliga" },
  { id: "liga3", name: "3. Liga" }, // Neu dazu
  { id: "dfb_pokal", name: "DFB Pokal" },
  { id: "champions_league", name: "Champions League" },
  { id: "europa_league", name: "Europa League" },
  { id: "conference_league", name: "Conference League" },
  { id: "supercup", name: "Supercup" },
  { id: "em_wm", name: "EM / WM" },
];

export const TEAMS = [
  // --- 1. Bundesliga ---
  { name: "1. FC Heidenheim", league: "bundesliga" },
  { name: "1. FC Union Berlin", league: "bundesliga" },
  { name: "1. FSV Mainz 05", league: "bundesliga" },
  { name: "1. FC Köln", league: "bundesliga" },
  { name: "Bayer 04 Leverkusen", league: "bundesliga" },
  { name: "Borussia Dortmund", league: "bundesliga" },
  { name: "Borussia Mönchengladbach", league: "bundesliga" },
  { name: "Eintracht Frankfurt", league: "bundesliga" },
  { name: "FC Augsburg", league: "bundesliga" },
  { name: "FC Bayern München", league: "bundesliga" },
  { name: "FC St. Pauli", league: "bundesliga" },
  { name: "Hamburger SV", league: "bundesliga" },
  { name: "RB Leipzig", league: "bundesliga" },
  { name: "SC Freiburg", league: "bundesliga" },
  { name: "SV Werder Bremen", league: "bundesliga" },
  { name: "TSG 1899 Hoffenheim", league: "bundesliga" },
  { name: "VfB Stuttgart", league: "bundesliga" },
  { name: "VfL Wolfsburg", league: "bundesliga" },

  // --- 2. Bundesliga ---
  { name: "1. FC Kaiserslautern", league: "bundesliga2" },
  { name: "1. FC Magdeburg", league: "bundesliga2" },
  { name: "Arminia Bielefeld", league: "bundesliga2" },
  { name: "Dynamo Dresden", league: "bundesliga2" },
  { name: "Eintracht Braunschweig", league: "bundesliga2" },
  { name: "FC Schalke 04", league: "bundesliga2" },
  { name: "Fortuna Düsseldorf", league: "bundesliga2" },
  { name: "Hannover 96", league: "bundesliga2" },
  { name: "Hertha BSC", league: "bundesliga2" },
  { name: "Holstein Kiel", league: "bundesliga2" },
  { name: "Karlsruher SC", league: "bundesliga2" },
  { name: "Preußen Münster", league: "bundesliga2" },
  { name: "SC Paderborn 07", league: "bundesliga2" },
  { name: "SpVgg Greuther Fürth", league: "bundesliga2" },
  { name: "SSV Ulm 1846", league: "bundesliga2" },
  { name: "SV Darmstadt 98", league: "bundesliga2" },
  { name: "SV Elversberg", league: "bundesliga2" },
  { name: "VfL Bochum", league: "bundesliga2" },

  // --- 3. Liga ---
  { name: "1. FC Saarbrücken", league: "liga3" },
  { name: "1. FC Schweinfurt 05", league: "liga3" },
  { name: "Alemannia Aachen", league: "liga3" },
  { name: "Energie Cottbus", league: "liga3" },
  { name: "FC Erzgebirge Aue", league: "liga3" },
  { name: "FC Ingolstadt 04", league: "liga3" },
  { name: "Hansa Rostock", league: "liga3" },
  { name: "MSV Duisburg", league: "liga3" },
  { name: "Rot-Weiss Essen", league: "liga3" },
  { name: "SC Verl", league: "liga3" },
  { name: "SSV Jahn Regensburg", league: "liga3" },
  { name: "SV Waldhof Mannheim", league: "liga3" },
  { name: "SV Wehen Wiesbaden", league: "liga3" },
  { name: "TSG 1899 Hoffenheim II", league: "liga3" },
  { name: "TSV 1860 München", league: "liga3" },
  { name: "TSV Havelse", league: "liga3" },
  { name: "VfB Stuttgart II", league: "liga3" },
  { name: "VfL Osnabrück", league: "liga3" },
  { name: "Viktoria Köln", league: "liga3" },
];
